name: "Mirror Repository Action"
description: "Mirror a GitHub Repository to Remote Host like Codeberg, Forgejo, GitLab and More"
author: "Shane"
branding:
  icon: "git-merge"
  color: "black"

inputs:
  url:
    description: "Remote Repository URL"
  host:
    description: "Remote Repository Host"
  owner:
    description: "Remote Repository Owner"
  repo:
    description: "Remote Repository Name"
  create:
    description: "Create Remote Repository"
  username:
    description: "Remote Repository Username"
  password:
    description: "Remote Repository Password"
  summary:
    description: "Add Summary to Job"
    default: "true"
  private:
    description: "Private Repository"
    default: "${{ github.event.repository.private }}"

runs:
  using: "docker"
  image: "Dockerfile"
