name: "Mirror Repository Action"
description: "Mirror a GitHub Repository to Remote Host like Codeberg, Forgejo, GitLab and More"
author: "Shane"
branding:
  icon: "git-merge"
  color: "black"

inputs:
  url:
    description: "Remote Repository URL"
    required: false
  host:
    description: "Remote Repository Host"
    required: false
  owner:
    description: "Remote Repository Owner"
    required: false
  repo:
    description: "Remote Repository Name"
    required: false
  create:
    description: "Create Remote Repository"
    required: false
  username:
    description: "Remote Repository Username"
    required: false
  password:
    description: "Remote Repository Password"
    required: false
  summary:
    description: "Add Summary to Job"
    required: false
    default: "true"
  private:
    description: "Private Repository"
    required: false
    default: "${{ github.event.repository.private }}"

runs:
  using: "docker"
  image: "Dockerfile"
