name: "Mirror"

on:
  workflow_dispatch:
  release:
    types: ["published"]
  push:
    branches: ["**"]
    tags: ["**"]

jobs:
  mirror:
    name: "Mirror"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Mirror to Codeberg"
        uses: cssnr/mirror-repository-action@master
        with:
          #url: https://codeberg.org/cssnr/mirror-repository-action
          host: https://codeberg.org
          #owner: cssnr
          #repo: mirror-repository-action
          create: true
          username: shaner
          password: ${{ secrets.CODEBERG_TOKEN }}
