name: "Lint"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      #- name: "Debug event.json"
      #  run: |
      #    cat "${GITHUB_EVENT_PATH}"

      - name: "ShellCheck"
        if: ${{ always() }}
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "src"
          check_together: "yes"

      - name: "Prettier"
        if: ${{ always() }}
        run: |
          npm install prettier
          npx prettier --check .
