name: "Test"

# NOTE: Job test mirror's the action so there is no mirror.yaml workflow...

on:
  workflow_dispatch:
  release:
    types: ["published"]
  push:
    branches: ["**"]
    tags: ["**"]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Test Local Action"
        id: test
        uses: ./
        with:
          #url: https://codeberg.org/cssnr/mirror-repository-action
          host: https://codeberg.org
          #owner: cssnr
          #repo: mirror-repository-action
          create: true
          username: shaner
          password: ${{ secrets.CODEBERG_TOKEN }}

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Run ShellCheck"
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: "src"
          check_together: "yes"
