name: "Test"

# NOTE: This job mirror's the repository so there is no mirror.yaml.

on:
  workflow_dispatch:
  push:
    branches: ["**"]
    tags: ["**"]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      #- name: "Debug CTX github"
      #  continue-on-error: true
      #  env:
      #    GITHUB_CTX: ${{ toJSON(github) }}
      #  run: echo "$GITHUB_CTX"

      - name: "Test Local Action"
        id: test
        uses: ./
        with:
          #url: https://codeberg.org/cssnr/mirror-repository-action
          host: https://codeberg.org
          #owner: cssnr
          #repo: mirror-repository-action
          create: true
          username: shaner
          password: ${{ secrets.CODEBERG_TOKEN }}

      #- name: "Schedule Failure Notification"
      #  if: ${{ failure() && github.event_name == 'schedule' }}
      #  uses: sarisia/actions-status-discord@v1
      #  with:
      #    webhook: ${{ secrets.DISCORD_WEBHOOK }}
